# -*- coding: utf-8 -*-
"""Salary_expectation_based_on_experience0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18B5HWO_VSRvsJC4WChFaP_RtJvj0hvAf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("Salary.csv")

data.head()

data.tail()

data.columns

data.describe()

data.info()

data.isnull().any()

data.isnull().sum()

plt.plot(data['Salary'],data['YearsExperience'])

f,ax=plt.subplots(figsize=(20,10))
corr=data.corr("pearson")
sns.heatmap(corr,mask=np.zeros_like(corr,dtype=np.bool),cmap=sns.diverging_palette(220,10,as_cmap=True),square=True,ax=ax,annot=True)

from sklearn.model_selection import train_test_split
x=data.drop('Salary',axis=1)

y=data['Salary']

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
L=LinearRegression()

L.fit(xtrain,ytrain)

y_pred=L.predict(xtest)

print(L.score(xtest,ytest))

print("actual salary",y)
print("predicted salary",y_pred)